controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.55
    wheel_radius: 0.15

    # Linear velocity limits
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.5
    linear.x.min_acceleration: -0.5

    # Angular velocity limits
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 0.5
    angular.z.min_acceleration: -0.5

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    
    wheels_per_side: 2  # Important for four-wheeled robot
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    enable_odom_tf: true
    
    base_frame_id: base_link
    odom_frame_id: odom
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    
    publish_limited_velocity: true
    use_stamped_vel: false
    
    # Additional parameters
    open_loop: true
    enable_twist_cmd: true
    
    # New parameters for better control
    linear_scale: 1.0
    angular_scale: 1.0
    
    # Wheel synchronization
    wheel_synchronization: true